# Standards: 0.11
---
# 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)

- name: Install the SE Linux requirements
  yum:
    name:
      - libselinux-python
      - policycoreutils-python
    state: installed
  retries: 3
  delay: 2
  tags:
    - level-2
    - section-1
    - "1.6.11"
    - scored

- name: 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)
  selinux:
    policy: targeted
    state: enforcing
  tags:
    - level-2
    - section-1
    - "1.6.11"
    - scored
