# Standards: 0.11
---

# 3.1.1 Ensure IP forwarding is disabled

- name: 3.1.1 - Ensure IP v4 forwarding is disabled
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Ensure IP v6 forwarding is disabled
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 0
    state: present
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored

- name: 3.1.1 - Ensure IP forwarding is disabled in active kernel parameters
  sysctl:
    name: "{{ item.name }}"
    sysctl_set: yes
    value: "{{ item.value }}"
  with_items:
    - name: "net.ipv4.ip_forward"
      value: 0
    - name: "net.ipv6.conf.all.forwarding"
      value: 0
    - name: "net.ipv4.route.flush"
      value: 1
    - name: "net.ipv6.route.flush"
      value: 1
  tags:
    - level-1
    - section-3
    - "3.1.1"
    - scored
