# Standards: 0.11
---

# 3.2.8 Ensure TCP SYN Cookies is enabled

- name: 3.2.8 - Ensure TCP SYN Cookies is enabled 
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.8"
    - scored


- name: 3.2.8 - Ensure TCP SYN Cookies is enabledin active kernel parameters
  sysctl:
    name: "{{ item.name }}"
    sysctl_set: yes
    value: "{{ item.value }}"
  with_items:
    - name: "net.ipv4.tcp_syncookies"
      value: 1
    - name: "net.ipv4.route.flush"
      value: 1
  tags:
    - level-1
    - section-3
    - "3.2.8"
    - scored
