# Standards: 0.11
---

# 3.2.6 Ensure bogus ICMP responses are ignored 

- name: 3.2.6 - Ensure bogus ICMP responses are ignored  
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
  tags:
    - level-1
    - section-3
    - "3.2.6"
    - scored

- name: 3.2.6 - Ensure bogus ICMP responses are ignored in active kernel parameters
  sysctl:
    name: "{{ item.name }}"
    sysctl_set: yes
    value: "{{ item.value }}"
  with_items:
    - name: "net.ipv4.icmp_ignore_bogus_error_responses"
      value: 1
    - name: "net.ipv4.route.flush"
      value: 1
  tags:
    - level-1
    - section-3
    - "3.2.6"
    - scored
