# Standards: 0.11
---

# 5.2.3 Ensure permissions on SSH public host key files are configured

- name: 5.2.3 - Ensure permissions on SSH public host key files are configured
  shell: "find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chmod 0644 {} \\;"
  tags:
    - sshd
    - level-1
    - section-4
    - "5.2.3"
    - scored

- name: 5.2.3 - Ensure permissions on SSH public host key files are configured
  shell: "find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chown root:root {} \\;"
  tags:
    - sshd
    - level-1
    - section-4
    - "5.2.3"
    - scored