# Standards: 0.11
---

# 5.2.2 Ensure permissions on SSH private host key files are configured

- name: 5.2.2 Ensure permissions on SSH private host key files are configured
  shell: "find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chown root:ssh_keys {} \\;"
  tags:
    - sshd
    - level-1
    - section-4
    - "5.2.2"
    - scored

- name: 5.2.2 Ensure permissions on SSH private host key files are configured
  shell: "find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chmod 0640 {} \\;"
  tags:
    - sshd
    - level-1
    - section-4
    - "5.2.2"
    - scored